# Generated by Django 5.2.11 on 2026-03-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skip_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
