# Generated by Django 5.2.11 on 2026-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pending_ocr_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
