# Generated by Django 5.2.11 on 2026-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_studynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
