# Generated by Django 5.2.11 on 2026-03-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_add_message_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='parsed_subjects_for_setup',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
