# Generated by Django 5.2.11 on 2026-03-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_add_parsed_subjects_for_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='parent_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
