# Generated by Django 5.2.11 on 2026-03-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_add_studynote_parent_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studynote',
            name='content',
        ),
    ]
