# Generated by Django 5.2.11 on 2026-03-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_remove_studynote_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studynote',
            old_name='topic_title',
            new_name='topic_content',
        ),
    ]
