# Generated by Django 5.2.11 on 2026-03-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_rename_topic_title_studynote_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='studynote',
            old_name='topic_content',
            new_name='topic_title',
        ),
    ]
