# Generated by Django 5.2.11 on 2026-03-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_revert_studynote_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studynote',
            name='content',
        ),
    ]
