# Generated by Django 5.2.11 on 2026-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_remove_studynote_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='setup_step',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
