# Generated by Django 5.2.11 on 2026-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_rename_timetable_u_user_id_2fdf54_idx_timetable_u_user_id_3bf139_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='curriculum',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
