# Generated by Django 5.2.11 on 2026-03-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_topic_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='curriculum',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
