# Generated by Django 5.2.11 on 2026-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_topic_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_overdue',
            field=models.BooleanField(default=False, help_text="Whether this topic's target date has passed"),
        ),
        migrations.AddField(
            model_name='topic',
            name='target_date',
            field=models.DateField(blank=True, help_text='Deadline for completing this topic', null=True),
        ),
    ]
