# Generated by Django 5.2.11 on 2026-03-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_add_topic_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
