# Generated by Django 5.2.11 on 2026-03-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_topic_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='session_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
